### ISSUE TITLE
Support for enabling compass in ScssphpFilter should be removed

### ISSUE THREAD

**Issue by stof** [assetic-php/assetic#10]
The `scss_compass` class belongs to `leafo/scssphp-compass` (or one of its [published forks](https://packagist.org/?query=scssphp%20compass)).

This package was never released, is not maintained anymore (last commit in 2012) and is for `leafo/scssphp`, not `scssphp/scssphp`. The last point means that the code is broken in Assetic, as ScssphpFilter uses the class from `scssphp/scssphp`.

**Comment by bennothommo** [comment]
Thanks for the report @stof. Shall be fixed by #17.
