### ISSUE TITLE
Custom functions in ScssphpFilter are not exposing the full upstream API

### ISSUE THREAD

**Issue by stof** [assetic-php/assetic#11]
`ScssphpFilter::registerFunction` only exposes arguments for the name and the callable.
But the ScssPhp API supports a third argument to configure the Sass signature (or signatures) of the function, and this parameter is not exposed in any way in Assetic.
Currently, this parameter is optional, with a different behavior when you don't have it or you have it. and the behavior without knowing the signature is not spec-compliant (as the compiler is expected to validate the signature). As such, the plan is to make that argument mandatory in 2.0 of scssphp. It would be great if Assetic could allow using this argument.

Note that we currently plan a refactoring in scssphp which will impact the implementation of custom functions, for which we plan to add a new (optional) argument in `registerFunction` to opt-in for the new behavior (which also won't allow omitting the signature). Once that argument appears, it might make sense to support it too (forcing the value to opt-in or opt-out in ScssphpFilter itself would defeat the purpose of the per-function opt-in)

**Comment by LukeTowers** [comment]
@stof just seeing this one now too, are you able to submit a PR for this or link to more details?

**Comment by stof** [comment]
See https://scssphp.github.io/scssphp/docs/extending/custom-functions.html for the doc about custom functions in scssphp.

Regarding the future argument to opt-in for a new signature for the callable, it is related to https://github.com/scssphp/scssphp/issues/265 but there is not a lot of details about the `registerFunction` change yet in it (the idea is that we would have a new boolean argument added in the signature to opt-in)

**Comment by stof** [comment]
I won't be able to submit a PR for that. I haven't used Assetic since years, so I prefer spending my time on other open-source work. I opened this issue due to being a scssphp maintainer, and finding that the Assetic filter was not compatible with our planned changes (not declaring arguments is now deprecated since our 1.5.0 release), not due to being an Assetic user.

**Comment by LukeTowers** [comment]
Fair enough, thanks @stof! @jaxwilko or @bennothommo do either of you have time to look into this?

**Comment by jaxwilko** [comment]
@LukeTowers I'm not going to have much time for the next 2 weeks but if nobody has looked by then I can pick it up :)

**Comment by bennothommo** [comment]
I can try take a look at it in the next couple of days.

**Comment by bennothommo** [comment]
Was longer than a couple of days, but #25 should provide the additional argument from the upstream API. 😛
