### ISSUE TITLE
CssMin not found error when using the filter CssMinFilter

### ISSUE THREAD

**Issue by prhost** [assetic-php/assetic#12]
Hi,

I'm getting this error when using filter `CssMinFilter` Do I need to install anything else?

![Screen Shot 2020-11-25 at 19 04 59](https://user-images.githubusercontent.com/3984760/100286255-3d2abe80-2f51-11eb-8607-c6c8d0e424db.png)

**Comment by bennothommo** [comment]
@prhost You need to ensure that `natxet/cssmin` is in your `composer.json` when using the `CssMinFilter`.
