### ISSUE TITLE
What happend to `CompilerJarFilter`?

### ISSUE THREAD

**Issue by fabiang** [assetic-php/assetic#13]
What the reason why `CompilerJarFilter` was removed from the 2.0 release?

**Comment by bennothommo** [comment]
@fabiang we have dropped support for filters that are not PHP or Node/JS-based, to minimise the scope of maintenance and target modern libraries and frameworks.

Filters such as the Google Closure JAR compiler can certainly be provided by third-party extensions to this library, if someone was willing to develop that.

**Comment by fabiang** [comment]
Thanks for the info. I've a drop-in replacement here which works with PHP 7.4: https://github.com/fabiang/assetic-google-closure-compiler
