### ISSUE TITLE
php 8.0

### ISSUE THREAD

**Issue by tzalexander** [assetic-php/assetic#19]
Hi,

is it possible for you to provide this package for php 8.0 too? I'm not able to install it with the current composer settings.

Following error is shown:
- assetic/framework v2.0.0 requires php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.

But in the composer.json the requirements should be met ("php": "^7.2|^8.0")?!

Thank you, Best Regards

**Comment by lopes-vincent** [comment]
Hi,
you can do `composer require assetic/framework dev-develop#b067e1779fc18db43031a4dc9a80308465febcfd` to require the latest commit on develop branch while there is no official release for a php 8 compatible version.   
But this is not "future-proof" and you will be stuck on this commit.

So does anyone know when the new version will be released ? 🙂

Thanks

**Comment by FabianKoestring** [comment]
Any news on this?

**Comment by Freespacer** [comment]
We included the package rwoverdijk/assetmanager for PHP 8 that needed assetic/framework package. The package rwoverdijk/assetmanager is ready for PHP 8 but required 2.0 without PHP 8 Support. It produced PHP version conflicts and can not solved with the current version.

Currently we use a nasty workaround in composer.json:
`"require": {
    "assetic/framework": "dev-master as 2.0"
}`

We would be appreciated that we can get a new package version with official support for PHP 8.

Thank you.

**Comment by LukeTowers** [comment]
@tzalexander @lopes-vincent @FabianKoestring @Freespacer new version (2.0.1) has been released, apologies for the delay, notifications were broken.
