### ISSUE TITLE
JSMin not found when using JSMinFilter

### ISSUE THREAD

**Issue by parktrip** [assetic-php/assetic#20]
I have mrclay/minify component installed as well.

In class Assetic\Filter\JSMinFilter, JsMin is called like this:
```
public function filterDump(AssetInterface $asset)
    {
        $asset->setContent(\JSMin::minify($asset->getContent()));
    }
```
except that there is no root class JSMin declared in mrclay module, only class JSMin\JSMin exists.

so changing Assetic\Filter\JSMinFilter like this solve the issue

```
<?php namespace Assetic\Filter;

use Assetic\Contracts\Asset\AssetInterface;
use JSMin\JSMin;

/**
 * Filters assets through JsMin.
 *
 * All credit for the filter itself is mentioned in the file itself.
 *
 * @link https://raw.github.com/mrclay/minify/master/min/lib/JSMin.php
 * @author Brunoais <brunoaiss@gmail.com>
 */
class JSMinFilter extends BaseFilter
{
    public function filterDump(AssetInterface $asset)
    {
        $asset->setContent(JSMin::minify($asset->getContent()));
    }
}
```
am i something wrong that I have to change this file in order to make it work ? Or did the class namespace and declaration from mrclay changed ?

Thank you in advance

**Comment by LukeTowers** [comment]
@parktrip apologies for only getting back to you now, notifications were broken.

According to https://github.com/mrclay/minify/blob/c80add80a210b29a5f45d7c66b664748ab05544c/CHANGELOG.md#300---2017-04-03 JSMin was removed in 3.0, you should be able to require the dependency like this `"mrclay/minify": "<2.3",` and have it work though.
