### ISSUE TITLE
PHP Fatal error:  Interface 'Assetic\Factory\Worker\WorkerInterface' not found.

### ISSUE THREAD

**Issue by jarrettj** [assetic-php/assetic#22]
Hey,

Good day.

Seems kriswallsmith assetic has been replaced by assetic-php. I have a custom LastModifiedStrategy which worked fine but now throws the error:
```
PHP Fatal error:  Interface 'Assetic\Factory\Worker\WorkerInterface' not found...
```

If I replace the Assetic\Factory\Worker\WorkerInterface with Assetic\Contracts\Factory\Worker\WorkerInterface instead, the new error is:
```
Argument 1 passed to AsseticBundle\Service::setCacheBusterStrategy() must be an instance of Assetic\Factory\Worker\WorkerInterface
```

Been trying to revert my composer file to a previous version, but can't seem to get kriswallsmith version installed again.

Any assistance would be much appreciated, thanks.

Regards.
Jarrett

**Comment by LukeTowers** [comment]
@jarrettj thanks for the report! Could you share the code you had used previously? I'm sure we can make an adjustment so that assetic-php will work with your code without requiring any changes on your end, although we'll also provide you the recommended way of doing what you're trying to do going forward.

**Comment by LukeTowers** [comment]
@jarrettj are you still interested in getting this resolved?

**Comment by jarrettj** [comment]
Hey @LukeTowers 

Thanks for reaching out. We have not picked this up yet. And probably wont for the next couple of months. Tech debt pile, you know how it goes :|. TBH I can't even clearly remember the issue, but I know I encountered it while trying to move away from outdated/abandoned packages.

Regards.
JJ
