### ISSUE TITLE
CSS Minifier Invalidly Shortening 8-Character Hex Codes

### ISSUE THREAD

**Issue by monterarty** [assetic-php/assetic#41]
**Issue Summary:**
The CSS minifier incorrectly shortens 8-character hex codes that include transparency information. For instance, it converts `#00000029` to `#00029,` which is not valid as the transparency in hex codes requires the full 8-character format.

**Steps to Reproduce:**

Use a CSS file that includes an 8-character hex code for color with transparency, such as `#00000029`.
Run the CSS file through the minifier.
Observe the output where the 8-character hex code is shortened incorrectly.

**Expected Behavior:**
The CSS minifier should retain the full 8-character hex code for colors that include transparency information. For example, `#00000029` should remain unchanged.

**Actual Behavior:**
The CSS minifier shortens the 8-character hex code incorrectly. For example, `#00000029` is converted to `#00029`, which is not a valid CSS hex code.

**Comment by LukeTowers** [comment]
Which Assetic filter are you using @monterarty?

**Comment by bennothommo** [comment]
@LukeTowers it appears to be the `StylesheetMinifyFilter` that October CMS wrote.

**Comment by bennothommo** [comment]
Thanks for the report @monterarty - fixed in https://github.com/assetic-php/assetic/commit/1249d92065cde96e38902ac471a8a92dc8d0d6a8.
